### ISSUE TITLE
AP and connect to a network with single device?

### ISSUE THREAD

**Issue by AshWhitear** [garywill/linux-router#13]
Hey there, 

Just wondered if this is possible? 

Great work on this btw, its brill.

Thanks, Ash.

**Comment by garywill** [comment]
Yes, wIll work, if your adapter supports.
Your `wlan0` connected to a network. A virtual `x0wlan0` will be created to be hotspot.(Many adapter requires `wlan0` and `x0wlan0` on same channel)

**Comment by chromer030** [comment]
If your adapter supports WiFi Direct, it can be used automatically for this purpose.

**Comment by AshWhitear** [comment]
Perfect, will give it a crack and report back - thanks both for such a speedy response!
