### ISSUE TITLE
How to apply lnx router to make transparent proxy in proxmox?

### ISSUE THREAD

**Issue by ghost** [garywill/linux-router#15]
hi, i want to make transparent proxy in proxmox, it's possible to use this script to create network card, and assign DHCP ip range to this network card, so that i can select VMBR1 for VM, to route all traffic truth proxy server. thanks, best regards

**Comment by garywill** [comment]
Hi, I haven't ever used proxmox before.
For a quick reply, I give you [this issue link](https://github.com/garywill/linux-router/issues/6). It's a question by a user about setting up transparent proxy. Check if it helps you.
