### ISSUE TITLE
Wifi hotspot without internet

### ISSUE THREAD

**Issue by SomaGallai** [garywill/linux-router#16]
Hi,

I am trying to create a wifi hotspot, that works without internet connection and still I would be able to ssh to it from another computer. At the moment it is connected to another router and the hotspot is working as expected, but when there is no internet the SSH is not working.

**Comment by thisisagan** [comment]
metoo

**Comment by garywill** [comment]
Could you guys be more clear? I dont understand whats going on

**Comment by aiden-loroco** [comment]
I would also like this. The use case is we have an rpi running with no touch screen or user input device. If the box can't connect to the wifi it knows about, then we'd like it to turn into an ap that serves just a simple ui which the user can connect to (on their phone for example) and supply the local wifi ssid and pw. I'm running:

```
sudo ./lnxrouter --ap wlan0 test-hello -p test-hello --no-dns --no-dnsmasq -w 2
```

I can see the network on my phone, but it fails to login. Note that I added --no-dns as I was seeing dnsmasq errors, and i'm not sure i need dns for my application.

**Comment by SomaGallai** [comment]
Sorry for the inactivity, the issue was solved by creating a configuration file with all the settings that can be seen in the 'define_global_variables()' section of your software and a small script that does the following: 

- shutdown wifi
- enable the device/port wished to provide the AP
- service start create_ap

Hope this provide some help people still trying to achieve
