### ISSUE TITLE
mktemp: Invalid argument

### ISSUE THREAD

**Issue by jrabausch** [garywill/linux-router#21]
Hi, im using Alpine Linux 3.12 with BusyBox 1.31.1 and mktemp fails with `mktemp: Invalid argument`.
I had to change line 1238 to `CONFDIR="$(mktemp -d $TMPDIR/lnxrouter.${TARGET_IFACE}.conf.XXXXXX)"`.

mktemp requires 6 times X for the file/dir template.

Awesome script, best regards.

**Comment by garywill** [comment]
Hey thank you for feedback!
We should increase it to 6.
Do you want to make a PR to be a contributor? Or I can do it myself.

**Comment by jrabausch** [comment]
You can apply this small fix yourself.
I'll close the issue.

Best regards.
