### ISSUE TITLE
Feature request Wireguard Gateway

### ISSUE THREAD

**Issue by Saugjunkie** [garywill/linux-router#30]
Hello i would like the funktion that use wireguard as a VPN gateway that all the traffic trouh a tunnel from the linux router to the wireguard server.

What do you mean it is possible to integrate?

Merry Chtistmas

**Comment by garywill** [comment]
Although I didn't try with wg, I think `-o` can do 
https://github.com/garywill/linux-router#provide-an-interfaces-internet-to-another-interface
(after you manually finished connecting  VPN on Linux)
