### ISSUE TITLE
Syntax error: "(" unexpected (expecting "}")

### ISSUE THREAD

**Issue by MoActive** [garywill/linux-router#39]
Hi,

Downloaded the file and tried to run it, but keep getting this error:

610: Syntax error: "(" unexpected (expecting "}")

`is_5ghz_frequency() {
    [[ $1 =~ ^(49[0-9]{2})|(5[0-9]{3})$ ]]
}`

I can't see anything wrong here, but might just be me?

Operating system:
Kali Linux

**Comment by garywill** [comment]
Were you running with wifi connected?
Run this (with wifi connected), post the result:
```
iw dev <YOUR-WIFI-IFACE> link
```

**Comment by MoActive** [comment]
My bad, had to set executable permission first :)
