### ISSUE TITLE
Syntax error line number #662

### ISSUE THREAD

**Issue by trinityzhub** [garywill/linux-router#54]
`sudo lnxrouter --ap wlan0 MyAccessPoint -p MyPassPhrase`

## I got "syntax error" :
```
/usr/bin/lnxrouter: 622: /usr/bin/lnxrouter: Syntax error: "(" unexpected (expecting "}")
```

FYI: 

OS: Debian Linux
Wifi availability : Laptop attached Wifi
I changed the wifi access point by using the command `sudo iwconfig`

Ref:

```

is_5ghz_frequency() {
    [[ $1 =~ ^(49[0-9]{2})|(5[0-9]{3})$ ]]
}

```

**Comment by garywill** [comment]
Close due to long time stale. Reopen if there's still problem
