### ISSUE TITLE
iw warning and error

### ISSUE THREAD

**Issue by dca00** [garywill/linux-router#60]
Hi Gary,
I've been using `lnxrouter` on an older Linux, since you've helped me with installing `hostapd`. Now, I put it on a brand new Linux, and when I start it with the same command `--ap wlan0 Name -p password` it throws the following warning and error:

```
WARN:  Can't use 'iw' to operate interface 'wlan0'. trying 'iwconfig' (not as good as 'iw')...
ERR: Can't use 'iwconfig' to operate interface 'wlan0'.
```

Old: Fedora 26
New: Fedora 36

Is this newer Linux missing a package or is it a misconfiguration?

**Comment by garywill** [comment]
Have you installed `iw` or `wireless-tools`?
Do you have `iw` or `iwconfig` command in bash?

Are they on same hardware? Unsupported wlan adapter could cause that also.

**Comment by dca00** [comment]
iw is present, as a package and command
iwconfig is not present
wireless-tools is not an available package

NetworkManager has no problem enabling the hotspot with the wifi card that is there, so I assume that it is supported. Both are Atheros of about the same vintage.

**Comment by dca00** [comment]
Great tip! I forgot to turn "predictable device naming" off. Thanks again!
