### ISSUE TITLE
How can I get BSSID of the access point?

### ISSUE THREAD

**Issue by dca00** [garywill/linux-router#63]
Hi Gary,

I checked the output but found no BSSID. Is the hwaddr the same thing?
If not, how can I get BSSID of the hotspot?

Many thanks!

**Comment by garywill** [comment]
> Is the hwaddr the same thing?
yes

The MAC address of the wifi interface (or virtual wifi interface) , which can be manually modified or randomized by our lnxrouter script, is the BSSID of created AP
