### ISSUE TITLE
[Q] How to allow clients to communicate with eachother?

### ISSUE THREAD

**Issue by Kugeleis** [garywill/linux-router#64]
I run an access point with lnxrouter successfully with `./lnxrouter --ap wlp1s0 myap -p mypwd --daemon  --dhcp-dns 192.168.1.1`. But clients on the ap can't communicate between eachother. Clients of the dhcp router can communicate between eachother. How can I fix this?

Edit: The device I start lnxrouter on spans it's own IP range. That's why I do not see the devices in the DHCP list. Can I set up lnxrouter to run as an IP client in 192.168.1.0?

**Comment by garywill** [comment]
Close due to long time stale. 

Theorically clients should have been able to communicate. Reopen and provide more info if there's problem
