### ISSUE TITLE
iw version 6.7 prints frequency differently

### ISSUE THREAD

**Issue by kphanipavan** [garywill/linux-router#67]
![Screenshot_20240107_090134](https://github.com/garywill/linux-router/assets/60005847/e0b16d31-652c-444e-ae22-2fc144a06b3a)

Current frequency taken from `iw` now prints differently now, as shown above.

Changes related to that is shown in the diff: https://fossies.org/diffs/iw/5.19_vs_6.7/info.c-diff.html

The number after the dot is the frequency offset. The awk script requires changes to handle this. Below is the error thrown currently.

![Screenshot_20240107_090503](https://github.com/garywill/linux-router/assets/60005847/f1078ceb-2367-468c-a11c-95150d41ecd3)

~Pvn

**Comment by kphanipavan** [comment]
Before:
![image](https://github.com/garywill/linux-router/assets/60005847/0f08c1df-6e7c-4f90-b529-de07b1b31596)

After, using `cut`:
![Screenshot_20240107_091341](https://github.com/garywill/linux-router/assets/60005847/c99e815d-81c1-4c8a-9f22-2240145c65d7)

Works on my end.

**Comment by garywill** [comment]
Thank you for reporting. We should take reaction to that change.

I'm still using a distro that using iw 4.9. So are you or anyone willing to make a PR?

**Comment by petebueh** [comment]
I copied the changes from this commit from linux-wifi-hotspot:
https://github.com/lakinduakash/linux-wifi-hotspot/commit/2dc1649add81854b79903dd16d59fcbbfa2fd8d3

This works for my AP

**Comment by garywill** [comment]
https://github.com/garywill/linux-router/commit/32f168ec8c9a69e022ae97d3bfd113fe088626d6 
I made `can_transmit_to_channel()` ignores freq value and just focus on channel number

```bash
grep -E " [0-9]+(\.[0-9]+){0,1} MHz \[${CHANNEL_NUM}\]"
```
